# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server_pb2 as server__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Criar = channel.unary_unary(
                '/servidor.Greeter/Criar',
                request_serializer=server__pb2.CriarCanalRequest.SerializeToString,
                response_deserializer=server__pb2.ResponseCriarCanal.FromString,
                _registered_method=True)
        self.Remover = channel.unary_unary(
                '/servidor.Greeter/Remover',
                request_serializer=server__pb2.RemoverCanalRequest.SerializeToString,
                response_deserializer=server__pb2.RemoverCanalResponse.FromString,
                _registered_method=True)
        self.ReceberMensagem = channel.unary_unary(
                '/servidor.Greeter/ReceberMensagem',
                request_serializer=server__pb2.MensagemRequest.SerializeToString,
                response_deserializer=server__pb2.MensagemResponse.FromString,
                _registered_method=True)
        self.Assinar = channel.unary_stream(
                '/servidor.Greeter/Assinar',
                request_serializer=server__pb2.AssinaturaRequest.SerializeToString,
                response_deserializer=server__pb2.MensagemResponse.FromString,
                _registered_method=True)
        self.AssinaturaStream = channel.stream_stream(
                '/servidor.Greeter/AssinaturaStream',
                request_serializer=server__pb2.AssinaturaRequest.SerializeToString,
                response_deserializer=server__pb2.MensagemResponse.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The greeting service definition.
    """

    def Criar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceberMensagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Assinar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssinaturaStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Criar': grpc.unary_unary_rpc_method_handler(
                    servicer.Criar,
                    request_deserializer=server__pb2.CriarCanalRequest.FromString,
                    response_serializer=server__pb2.ResponseCriarCanal.SerializeToString,
            ),
            'Remover': grpc.unary_unary_rpc_method_handler(
                    servicer.Remover,
                    request_deserializer=server__pb2.RemoverCanalRequest.FromString,
                    response_serializer=server__pb2.RemoverCanalResponse.SerializeToString,
            ),
            'ReceberMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceberMensagem,
                    request_deserializer=server__pb2.MensagemRequest.FromString,
                    response_serializer=server__pb2.MensagemResponse.SerializeToString,
            ),
            'Assinar': grpc.unary_stream_rpc_method_handler(
                    servicer.Assinar,
                    request_deserializer=server__pb2.AssinaturaRequest.FromString,
                    response_serializer=server__pb2.MensagemResponse.SerializeToString,
            ),
            'AssinaturaStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AssinaturaStream,
                    request_deserializer=server__pb2.AssinaturaRequest.FromString,
                    response_serializer=server__pb2.MensagemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servidor.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('servidor.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def Criar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidor.Greeter/Criar',
            server__pb2.CriarCanalRequest.SerializeToString,
            server__pb2.ResponseCriarCanal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidor.Greeter/Remover',
            server__pb2.RemoverCanalRequest.SerializeToString,
            server__pb2.RemoverCanalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceberMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servidor.Greeter/ReceberMensagem',
            server__pb2.MensagemRequest.SerializeToString,
            server__pb2.MensagemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Assinar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/servidor.Greeter/Assinar',
            server__pb2.AssinaturaRequest.SerializeToString,
            server__pb2.MensagemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssinaturaStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/servidor.Greeter/AssinaturaStream',
            server__pb2.AssinaturaRequest.SerializeToString,
            server__pb2.MensagemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
